"use client";
import {useEffect,useRef,useState} from 'react';
import {collectionCategories,type CollectionCategory,type CollectionSeller} from '../../lib/catalog-sellers';
type Result={name:string;status:string;price?:number;message?:string};
export function OasisCollectionPanel({onCollected}:{onCollected:()=>void}){
 const [seller,setSeller]=useState<CollectionSeller>('oasis'),[category,setCategory]=useState<CollectionCategory>('tofu'),[count,setCount]=useState('20');
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[results,setResults]=useState<Result[]>([]),[summary,setSummary]=useState('');
 const stop=useRef(false);
 useEffect(()=>()=>{stop.current=true;},[]);
 async function collect(){const target=Number(count);if(!Number.isInteger(target)||target<1||target>200){setError('1~200 사이의 정수를 입력해 주세요.');return;}stop.current=false;setBusy(true);setError('');setResults([]);setSummary('');let offset=0;try{while(offset<target&&!stop.current){const response=await fetch('/api/admin/catalog/collect',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({seller,category,count:target,offset})});const data=await response.json();if(!response.ok)throw new Error(data.error);setResults(previous=>[...previous,...data.results]);if(data.nextOffset<=offset||data.done){setSummary(data.stopped?'판매처에서 요청을 제한해 중단했습니다.':data.nextOffset<target?'해당 목록에서 더 확인할 상품이 없어요.':'수집이 완료됐어요.');break;}offset=data.nextOffset;}if(stop.current)setSummary('중지했어요. 완료된 상품은 저장되어 있습니다.');onCollected();}catch(e){setError(e instanceof Error?e.message:'수집 실패');onCollected();}finally{setBusy(false);}}
 return <section className="oasis-collection"><div><h2>🧺 판매처별 상품 수집</h2><small>판매처와 카테고리를 고르고 확인할 개수를 입력하세요. 신규 상품은 등록하고 기존 상품은 가격·사진을 갱신합니다. 영양정보는 임의로 채우지 않아요.</small></div><div className="catalog-collection-controls"><label>수집 판매처<select disabled={busy} value={seller} onChange={e=>setSeller(e.target.value as CollectionSeller)}><option value="oasis">오아시스</option><option value="kurly">컬리</option></select></label><label>수집 카테고리<select disabled={busy} value={category} onChange={e=>setCategory(e.target.value as CollectionCategory)}>{Object.entries(collectionCategories).map(([key,name])=><option key={key} value={key}>{name}</option>)}</select></label><label>확인할 상품 수<input disabled={busy} type="number" min="1" max="200" step="1" value={count} onChange={e=>setCount(e.target.value)}/></label></div><small>5개씩 순서대로 확인합니다. 중복 상품은 갱신하며, 카테고리 불일치·품절·옵션·가격 확인 실패는 제외되어 실제 등록 수는 적을 수 있어요. {seller==='kurly'?'컬리는 등록 상품부터 갱신하고 부족하면 공개 사이트맵을 탐색해요.':'오아시스는 선택한 카테고리의 공개 상품 목록을 탐색해요.'} 자동 실행이 끝날 때까지 이 화면을 유지해 주세요.</small><button type="button" disabled={busy} onClick={collect}>{busy?`${results.length}/${count}개 확인 중…`:`${seller==='oasis'?'오아시스':'컬리'} 상품 수집 시작`}</button>{busy&&<button type="button" onClick={()=>{stop.current=true;setSummary('현재 묶음이 끝나면 중지합니다.');}}>수집 중지</button>}{error&&<p role="alert">{error}</p>}<div role="status">{summary}{results.length>0&&<p>확인 {results.length}개 · 신규 {results.filter(r=>r.status==='inserted').length}개 · 갱신 {results.filter(r=>r.status==='updated').length}개 · 건너뜀 {results.filter(r=>r.status==='skipped').length}개</p>}</div>{results.length>0&&<details><summary>상품별 수집 결과 보기</summary><ul>{results.map((r,i)=><li key={i}>{r.name} — {r.status==='skipped'?r.message:`${r.status==='inserted'?'신규 등록':'갱신'} · ${r.price?.toLocaleString()}원`}</li>)}</ul></details>}</section>;
}
