import assert from 'node:assert/strict';
import {test} from 'node:test';
import {emptyAllergyInfo} from '../lib/catalog-allergy';
import type {CatalogItem} from '../lib/catalog';
import {cookingProducts,matchesCookingAlternative} from '../lib/cooking-recipes';
import {basketTotal,purchaseBasket,recommendShopping,initialConditions,parseConditions,candidates} from '../lib/shopping-plan';
import {availablePortions,consumeFood,restoreConsumption} from '../lib/food-intake';
import {sharedPlanSnapshot} from '../lib/shared-plan';
import alternatives from '../data/cooking-ingredient-alternatives.json';
const ingredient=(id:string,price:number,quantity:number,detail:string,unit:'g'|'개'='g'):CatalogItem=>({emoji:'🍚',portions:'1팩',protein:'',color:'',searchQuery:id,category:'ingredient',inWeeklyCart:false,productImageUrl:null,nutritionSourceName:null,nutritionPhotoUrl:null,carbohydratesG:null,fatG:null,sodiumMg:null,updatedAt:null,id,name:id,price,quantity,detail,unit,productUrl:'https://example.test/item',nutritionBasis:'100g당',caloriesKcal:100,proteinG:10,nutritionSourceUrl:'https://example.test/nutrition',allergens:[],allergyInfo:{...emptyAllergyInfo,status:'ingredients',statement:id}});
const catalog=[ingredient('rice',2000,210,'210g × 1개'),ingredient('tofu',2200,300,'300g × 1팩'),ingredient('eggs',7700,20,'20구 · 1팩','개'),ingredient('chicken',2090,100,'100g'),ingredient('kurly-5036690',6890,1,'600g · 1봉','개')];
const products=cookingProducts(catalog),tofu=products.find(p=>p.id==='cook-tofu-rice')!,egg=products.find(p=>p.id==='cook-egg-rice')!;
test('selected ingredient offer updates pack costs, consumption and restoration',()=>{
 const offer=alternatives.groups[0].offers[1];
 const source:CatalogItem={...ingredient(offer.id,6990,offer.quantity,offer.detail,'개'),name:offer.name,productUrl:offer.sourceUrl,market:'KR',currency:'KRW',priceCheckedAt:'2026-09-17T00:00:00Z'};
 const all=cookingProducts([...catalog,source]);
 const changed=all.find(p=>p.id===`cook-tofu-rice--with--${offer.id}`)!;
 assert.ok(changed);
 const veg=changed.recipe!.ingredients.find(i=>i.product.id===offer.id)!;
 assert.equal(veg.packs,120/500);
 assert.equal(changed.price,Math.round(2000+1100+6990*120/500));
 assert.equal(basketTotal([changed.id],all,[]),changed.price,'meal cost counts only the amount used');
 assert.equal(basketTotal([changed.id],all,[],{[offer.id]:.24}),2000+1100);
 const stock=Object.fromEntries(changed.recipe!.ingredients.map(({product:p})=>[p.id,{id:p.id,name:p.name,unit:'묶음',url:p.productUrl,ordered:0,owned:1}]));
 const consumed=consumeFood(stock,changed,1);
 assert.equal(consumed.stock[offer.id].owned,.76);
 assert.deepEqual(restoreConsumption(consumed.stock,consumed.snapshot,consumed.packs),stock);
 assert.ok(sharedPlanSnapshot({...initialConditions,days:1,meals:1},[changed.id],all)?.purchases?.some(p=>p.id===offer.id));
 assert.ok(!recommendShopping(all,{...initialConditions,mealMode:'cook',days:1,meals:1})!.some(id=>id.includes('--with--')));
 for(const patch of [{quantity:2},{currency:'JPY'},{priceCheckedAt:null},{detail:'다른 용량'},{productUrl:'https://example.test/changed'}])assert.ok(!cookingProducts([...catalog,{...source,...patch}]).some(p=>p.id.includes('--with--')));
});
test('multiple ingredient selections persist together; eggs use counts rather than shell weight',()=>{
 const fixtures=alternatives.groups.flatMap(g=>g.offers.map(o=>({...ingredient(o.id,3000,o.quantity,o.detail,o.unit as 'g'|'개'),name:o.name,productUrl:o.sourceUrl,market:'KR',currency:'KRW',priceCheckedAt:'2026-09-17T00:00:00Z'})));
 const all=cookingProducts([...catalog,...fixtures]);
 const rice=alternatives.groups.find(g=>g.baseId==='rice')!.offers[0];
 const eggOffer=alternatives.groups.find(g=>g.baseId==='eggs')!.offers[0];
 const tofuOffer=alternatives.groups.find(g=>g.baseId==='tofu')!.offers[0];
 const matches=(p:typeof tofu)=>p.id.startsWith('cook-tofu-egg--with--')&&[rice.id,eggOffer.id,tofuOffer.id].every(id=>p.recipe!.ingredients.some(i=>i.product.id===id));
 const combined=all.find(matches)!;assert.ok(combined);
 const parts=combined.recipe!.ingredients;
 assert.equal(parts.find(i=>i.product.id===rice.id)!.packs,105/1680);
 assert.equal(parts.find(i=>i.product.id===eggOffer.id)!.packs,2/10);
 assert.equal(parts.find(i=>i.product.id===tofuOffer.id)!.packs,150/500);
 assert.equal(combined.recipe!.nutrition.calories,null,'shell weight is not edible weight');
 assert.equal(purchaseBasket([combined.id],all,[]).length,3);
 assert.ok(Math.abs(basketTotal([combined.id],all,[])-combined.price)<=2,'usage-based cost matches the recipe price');
 const restored=cookingProducts([...catalog,...fixtures]).find(p=>p.id===combined.id);
 assert.deepEqual(restored,combined);
 const alternateRice=alternatives.groups.find(g=>g.baseId==='rice')!.offers[1];
 assert.ok(all.some(p=>p.id.startsWith('cook-tofu-egg--with--')&&[alternateRice.id,eggOffer.id,tofuOffer.id].every(id=>p.recipe!.ingredients.some(i=>i.product.id===id))));
});
test('two recipes share selling packs and preserve fractional leftovers',()=>{
 const ids=[tofu.id,egg.id],rows=purchaseBasket(ids,products,[]);
 assert.equal(rows.find(r=>r.product.id==='rice')?.packs,2);
 assert.equal(rows.find(r=>r.product.id==='kurly-5036690')?.packs,1);
 assert.equal(rows.find(r=>r.product.id==='kurly-5036690')?.left,0.6);
 assert.equal(basketTotal(ids,products,[]),rows.reduce((sum,r)=>sum+Math.round(r.required*r.product.price),0));
 assert.equal(basketTotal(ids,products,[],{'rice':2,'tofu':0.5,'eggs':0.1,'kurly-5036690':0.4}),0);
 assert.equal(purchaseBasket(ids,products,[],{}, {[tofu.id]:0,[egg.id]:0}).length,0);
});
test('recipe mode, exclusions, breakfast and budget are respected',()=>{
 assert.equal(products.length,7);
 assert.equal(candidates(products,{...initialConditions,mealMode:'ready'}).length,0);
 assert.equal(parseConditions({...initialConditions,mealMode:'invalid'}),null);
 assert.equal(candidates(products,{...initialConditions,excluded:['egg']}).some(p=>p.recipe?.ingredients.some(i=>i.product.id==='eggs')),false);
 const c={...initialConditions,mealMode:'cook' as const,days:2,meals:2,budget:20000};
 const ids=recommendShopping(products,c)!;assert.equal(ids.length,2);assert.ok(basketTotal(ids,products,[])<=c.budget);
 assert.equal(recommendShopping(products,{...c,budget:1000}),null);
 const week={...c,days:7,meals:7,budget:50000};
 const weekly=recommendShopping(products,week)!;
 assert.equal(new Set(weekly).size,7);
 assert.ok(basketTotal(weekly,products,[])<=week.budget);
 assert.equal(purchaseBasket(weekly,products,[]).length,5,'seven dishes reuse five ingredients');
});
test('changed selling units or incomplete ingredient catalog never invent a recipe',()=>{
 assert.equal(cookingProducts([]).length,0);
 assert.equal(cookingProducts(catalog.map(p=>p.id==='rice'?{...p,quantity:2520}:p)).length,0);
 const unknown=cookingProducts(catalog.map(p=>p.id==='tofu'?{...p,proteinG:null}:p)).find(p=>p.id===tofu.id)!;
 assert.equal(unknown.recipe?.nutrition.protein,null);
});
test('eating consumes only used ingredients and undo restores exact snapshots',()=>{
 const stock=Object.fromEntries(tofu.recipe!.ingredients.map(({product:p})=>[p.id,{id:p.id,name:p.name,unit:'묶음',url:p.productUrl,ordered:0,owned:1}]));
 const result=consumeFood(stock,tofu,1);
 assert.equal(availablePortions(stock,tofu),1);
 assert.equal(result.stock.tofu.owned,0.5);assert.equal(result.stock['kurly-5036690'].owned,0.8);assert.equal(result.stock.rice.owned,0);
 assert.equal(stock.tofu.owned,1);
 assert.deepEqual(restoreConsumption(result.stock,result.snapshot,result.packs),stock);
 assert.throws(()=>consumeFood({...stock,tofu:{...stock.tofu,owned:0}},tofu,1));
 assert.equal(stock.rice.owned,1);
});
test('shared plan retains meals but lists actual ingredients once',()=>{
 const snapshot=sharedPlanSnapshot({...initialConditions,days:2,meals:2},[tofu.id,egg.id],products)!;
 assert.equal(snapshot.products.length,2);assert.equal(snapshot.meals[0].productId,tofu.id);
 assert.equal(snapshot.purchases!.filter(p=>p.id==='kurly-5036690').length,1);
 assert.equal(snapshot.total,basketTotal([tofu.id,egg.id],products,[]));
});

test('comparison matches the main ingredient instead of merely sharing rice or porridge',()=>{
 const chicken=products.find(p=>p.id==='cook-chicken-porridge')!;
 const ready=(name:string)=>({...chicken,name,recipe:undefined});
 assert.equal(matchesCookingAlternative(chicken,ready('소고기버섯죽')),false);
 assert.equal(matchesCookingAlternative(chicken,ready('호박죽')),false);
 assert.equal(matchesCookingAlternative(chicken,ready('닭죽')),true);
 assert.equal(matchesCookingAlternative(egg,ready('계란볶음밥')),true);
 assert.equal(matchesCookingAlternative(egg,ready('새우 계란볶음밥')),false);
});
