import assert from 'node:assert/strict';
import {test} from 'node:test';
import {randomUUID} from 'node:crypto';
import {readFileSync} from 'node:fs';
import pg from 'pg';
import {NextRequest} from 'next/server';
import {getPool} from '../lib/db';
import {createSession,SESSION_COOKIE,type PublicUser} from '../lib/auth';
import {GET as catalog} from '../app/api/catalog/route';
import {GET as offers} from '../app/api/catalog/offers/route';
import {GET as expenses,PUT as saveExpense} from '../app/api/regional/expenses/route';
import {PUT as saveBudget,GET as budget} from '../app/api/regional/budgets/route';
import {PUT as saveRegion,GET as region} from '../app/api/region/route';
import {GET as dashboard,PUT as saveLegacyExpense} from '../app/api/dashboard/route';
import {POST as reset} from '../app/api/reset-data/route';
import {PUT as saveStock} from '../app/api/shopping-progress/route';

test('isolated migration, Japanese catalog, translations, currencies, budgets, preferences and reset',async()=>{
 const original=process.env.DATABASE_URL!;
 const admin=new pg.Client({connectionString:original});await admin.connect();
 const schema=`intl_test_${randomUUID().replaceAll('-','')}`;
 await admin.query(`CREATE SCHEMA "${schema}"`);
 const url=new URL(original);url.searchParams.set('options',`-c search_path=${schema}`);process.env.DATABASE_URL=url.toString();
 const db=getPool();
 const request=(path:string,cookie='',body?:unknown)=>new NextRequest(`http://localhost:3000${path}`,{method:body?'PUT':'GET',headers:{Cookie:cookie,origin:'http://localhost:3000','Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});
 try{
  assert.equal((await db.query('SELECT current_schema() AS s')).rows[0].s,schema);
  await db.query(readFileSync('db/schema.sql','utf8'));
  const user=(await db.query<PublicUser>("INSERT INTO users(name,email) VALUES('International test','intl@example.test') RETURNING id::text,name,email")).rows[0];
  await db.query("INSERT INTO daily_expenses(user_id,spent_on,category,amount) VALUES($1,'2026-09-17','food',9000)",[user.id]);
  const sql=readFileSync('db/internationalization.sql','utf8');await db.query(sql);await db.query(sql);
  const cookie=`${SESSION_COOKIE}=${(await createSession(user)).cookies.get(SESSION_COOKIE)!.value}`;
  const other=(await db.query<PublicUser>("INSERT INTO users(name,email) VALUES('Other account','other@example.test') RETURNING id::text,name,email")).rows[0];
  const otherCookie=`${SESSION_COOKIE}=${(await createSession(other)).cookies.get(SESSION_COOKIE)!.value}`;
  const old=(await db.query('SELECT market_code,currency_code,amount FROM daily_expenses')).rows[0];assert.deepEqual(old,{market_code:'KR',currency_code:'KRW',amount:9000});
  await db.query(`INSERT INTO catalog_items(id,name,detail,price,portions,quantity,search_query,market_code,currency_code,source_locale) VALUES('jp-test','日本の弁当','1個',850,'1食',1,'弁当','JP','JPY','ja-JP')`);
  await db.query("INSERT INTO catalog_translations VALUES('jp-test','ko-KR','일본 도시락','1개','1끼','도시락',NOW())");
  const jp=await(await catalog(request('/api/catalog?market=JP&locale=ja-JP'))).json();assert.equal(jp.items.length,1);assert.equal(jp.items[0].name,'日本の弁当');assert.equal(jp.region.currency,'JPY');assert.equal(jp.region.status,'preview');
  assert.equal((await(await catalog(request('/api/catalog?market=JP&locale=ko-KR'))).json()).items[0].name,'일본 도시락');
  assert.equal((await(await catalog(request('/api/catalog?market=JP&locale=en-US'))).json()).items[0].translationFallback,true);
  assert.ok(!(await(await catalog()).json()).items.some((p:{id:string})=>p.id==='jp-test'));
  assert.equal((await catalog(request('/api/catalog?market=XX'))).status,400);
  await db.query("INSERT INTO market_sellers VALUES('JP','test','Test seller','https://example.test')");
  await db.query("INSERT INTO catalog_offers(id,product_id,market_code,currency_code,seller_key,seller_product_id,price_minor,product_url,availability,checked_at,source_url) VALUES('offer','jp-test','JP','JPY','test','sku',850,'https://example.test/sku','in_stock',NOW(),'https://example.test/sku')");
  assert.equal((await(await offers(request('/api/catalog/offers?market=JP&product=jp-test'))).json()).offers[0].amountMinor,'850');
  assert.equal((await(await offers(request('/api/catalog/offers?market=KR&product=jp-test'))).json()).offers.length,0);
  const expense={market:'JP',currency:'JPY',date:'2026-09-17',category:'food',amountMinor:850};
  assert.equal((await saveExpense(request('/api/regional/expenses','',expense))).status,401);
  assert.equal((await saveExpense(request('/api/regional/expenses',cookie,{...expense,currency:'KRW'}))).status,400);
  assert.equal((await saveExpense(request('/api/regional/expenses',cookie,expense))).status,200);
  assert.equal((await(await expenses(request('/api/regional/expenses?market=JP&from=2026-09-17',otherCookie))).json()).totalMinor,0);
  await assert.rejects(db.query("INSERT INTO daily_expenses(user_id,market_code,currency_code,spent_on,category,amount) VALUES($1,'JP','KRW','2026-09-17','food',5)",[user.id]));
  const readExpenses=(market:string)=>expenses(request(`/api/regional/expenses?market=${market}&from=2026-09-17`,cookie));
  assert.equal((await(await readExpenses('JP')).json()).totalMinor,850);assert.equal((await(await readExpenses('KR')).json()).totalMinor,9000);
  assert.equal((await saveLegacyExpense(request('/api/dashboard',cookie,{action:'expense',date:'2026-09-17',category:'food',amount:10000}))).status,200);
  const legacy=await(await dashboard(request('/api/dashboard',cookie))).json();assert.equal(legacy.expenses.length,1);assert.equal(legacy.expenses[0].amount,10000);
  const purchase={stock:{rice:{id:'rice',name:'밥',unit:'묶음',url:null,ordered:1,owned:0}},version:0,expense:{id:randomUUID(),date:'2026-09-17',amount:2000,action:'order',itemIds:['rice']}};
  assert.equal((await saveStock(request('/api/shopping-progress?scope=products',cookie,purchase))).status,200);
  assert.equal((await(await readExpenses('KR')).json()).totalMinor,12000);
  assert.equal((await(await readExpenses('JP')).json()).totalMinor,850);
  const b={market:'JP',currency:'JPY',period:'month',start:'2026-09-01',amountMinor:30000};
  assert.equal((await saveBudget(request('/api/regional/budgets',cookie,b))).status,200);
  assert.equal((await(await budget(request('/api/regional/budgets?market=JP&period=month&start=2026-09-01',cookie))).json()).amountMinor,30000);
  assert.equal((await saveRegion(request('/api/region',cookie,{market:'JP',locale:'ja-JP',timeZone:'Asia/Tokyo'}))).status,200);
  assert.equal((await(await region(request('/api/region',cookie))).json()).region.currency,'JPY');
  assert.equal((await saveRegion(request('/api/region',cookie,{market:'JP',locale:'ja-JP',timeZone:'bad-zone'}))).status,400);
  await db.query("INSERT INTO market_workspaces(user_id,market_code,currency_code,locale_code,time_zone) VALUES($1,'JP','JPY','ja-JP','Asia/Tokyo')",[user.id]);
  const intake=()=>db.query("INSERT INTO market_meal_intakes(user_id,market_code,currency_code,id,meal_date,meal_slot,product_id,product_name,portions,locale_code,time_zone) VALUES($1,'JP','JPY',$2,'2026-09-17','lunch','jp-test','日本の弁当',1,'ja-JP','Asia/Tokyo')",[user.id,randomUUID()]);
  await intake();await assert.rejects(intake());
  assert.equal((await reset(request('/api/reset-data',cookie,{confirmation:'전체 초기화',userId:user.id}))).status,200);
  assert.equal((await db.query('SELECT count(*)::int AS n FROM daily_expenses')).rows[0].n,0);
  assert.equal((await db.query('SELECT count(*)::int AS n FROM market_workspaces')).rows[0].n,0);
  assert.equal((await(await region(request('/api/region',cookie))).json()).region.market,'KR');
 }finally{
  await db.end();process.env.DATABASE_URL=original;
  if(!/^intl_test_[0-9a-f]{32}$/.test(schema))throw new Error('Unexpected test schema');
  await admin.query(`DROP SCHEMA "${schema}" CASCADE`);await admin.end();
 }
});
