import assert from 'node:assert/strict';
import {test} from 'node:test';
import {randomUUID} from 'node:crypto';
import {NextRequest} from 'next/server';
import {GET,PUT,POST} from '../app/api/shopping-progress/route';
import {createSession,SESSION_COOKIE,type PublicUser} from '../lib/auth';
import {getPool} from '../lib/db';
import {initialConditions} from '../lib/shopping-plan';
const req=(cookie='',body?:unknown,scope='products',origin='http://localhost:3000')=>new NextRequest(`http://localhost:3000/api/shopping-progress?scope=${scope}`,{method:body?'PUT':'GET',headers:{Cookie:cookie,origin,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});
test('progress persists per account and scope; stale writes cannot overwrite newer receipts',async()=>{
 const db=getPool(),ids:string[]=[],cookies:string[]=[];
 try{
  assert.equal((await GET(req())).status,401);
  for(let i=0;i<2;i++){const user=(await db.query<PublicUser>("INSERT INTO users(name,email) VALUES('구매 상태 테스트',$1) RETURNING id::text,name,email",[`progress-${randomUUID()}@example.test`])).rows[0];ids.push(user.id);cookies.push(`${SESSION_COOKIE}=${(await createSession(user)).cookies.get(SESSION_COOKIE)!.value}`);}
  const stock={rice:{id:'rice',name:'밥',unit:'묶음',url:null,ordered:2,owned:0}};
  assert.equal((await PUT(req(cookies[0],{stock,version:0}))).status,200);
  assert.deepEqual((await(await GET(req(cookies[0]))).json()).stock,stock);
  assert.deepEqual((await(await GET(req(cookies[1]))).json()).stock,{});
  assert.deepEqual((await(await GET(req(cookies[0],undefined,'ingredients'))).json()).stock,{});
  assert.equal((await PUT(req(cookies[0],{stock,version:0}))).status,409);
  const received={rice:{...stock.rice,ordered:0,owned:2}};
  assert.equal((await PUT(req(cookies[0],{stock:received,version:1}))).status,200);
  assert.equal((await PUT(req(cookies[0],{stock,version:1}))).status,409);
  assert.deepEqual((await(await GET(req(cookies[0]))).json()).stock,received);
  assert.equal((await PUT(req(cookies[0],{stock,version:2},'products','https://evil.example'))).status,403);
  assert.equal((await PUT(req(cookies[0],{stock:{rice:{...stock.rice,owned:-1}},version:2}))).status,400);
  const importId=randomUUID();
  const merge=(cookie=cookies[0],targetUserId=ids[0],scope='products',guestStock=stock,id=importId)=>POST(req(cookie,{stock:guestStock,importId:id,targetUserId},scope));
  assert.equal((await merge('')).status,401);
  assert.equal((await merge(cookies[1])).status,409);
  const imports=await Promise.all([merge(),merge()]);
  assert.ok(imports.every(r=>r.status===200));
  const combined=(await(await GET(req(cookies[0]))).json());
  assert.equal(combined.stock.rice.ordered,2);
  assert.equal(combined.stock.rice.owned,2);
  assert.equal(combined.version,3);
  assert.equal((await merge(cookies[1],ids[1])).status,409);
  assert.equal((await merge(cookies[0],ids[0],'ingredients')).status,409);
  assert.equal((await merge(cookies[0],ids[0],'products',{rice:{...stock.rice,unit:'그램'}},randomUUID())).status,409);
  assert.equal((await PUT(req(cookies[0],{stock:received,version:3}))).status,200);
  assert.equal((await merge()).status,200);
  assert.deepEqual((await(await GET(req(cookies[0]))).json()).stock,received);
  await db.query('INSERT INTO shopping_plans(user_id,conditions,meal_ids) VALUES($1,$2,$3)',[ids[0],JSON.stringify(initialConditions),JSON.stringify(['rice'])]);
  const planCount=(await db.query('SELECT count(*)::int AS n FROM shopping_plans WHERE user_id=$1',[ids[0]])).rows[0].n;
  const reset={stock:{},version:4,resetConditions:initialConditions};
  assert.equal((await PUT(req('',reset))).status,401);
  assert.equal((await PUT(req(cookies[0],{...reset,version:3}))).status,409);
  assert.equal((await db.query('SELECT count(*)::int AS n FROM shopping_plans WHERE user_id=$1',[ids[0]])).rows[0].n,planCount);
  assert.equal((await PUT(req(cookies[0],reset,'ingredients'))).status,400);
  assert.equal((await PUT(req(cookies[0],reset))).status,200);
  assert.deepEqual((await(await GET(req(cookies[0]))).json()),{stock:{},version:5});
  const latest=(await db.query('SELECT conditions,meal_ids FROM shopping_plans WHERE user_id=$1 ORDER BY id DESC LIMIT 1',[ids[0]])).rows[0];
  assert.deepEqual(latest.meal_ids,[]);assert.equal(latest.conditions.budget,initialConditions.budget);
  assert.equal((await merge()).status,200);
  assert.deepEqual((await(await GET(req(cookies[0]))).json()).stock,{});
 }finally{await db.query('DELETE FROM users WHERE id=ANY($1::bigint[])',[ids]);await db.end();}
});
