'use client';
import {useState} from 'react';
import Link from 'next/link';
import './preview.css';
export type PreviewMeal={id:string;name:string;image:string|null;url:string|null;price:number|null;brand?:string;note:string;steps:string[];ingredients:string[];checkedAt:string|null};
type Mode='ready'|'simple'|'cook';
const options=[{id:'ready',icon:'🛍️',title:'오늘은 요리 안 할래요',sub:'사서 먹는 한 끼부터 찾아요'},{id:'simple',icon:'🥣',title:'간단한 준비는 괜찮아요',sub:'손질과 조리가 적은 메뉴'},{id:'cook',icon:'🍳',title:'직접 만들어 먹을래요',sub:'재료와 조리법을 보고 골라요'}] as const;
export function PrepPreview({groups,counts}:{groups:Record<Mode,PreviewMeal[]>;counts:Record<Mode|'catalog',number>}){
 const [mode,setMode]=useState<Mode>('ready');const [offset,setOffset]=useState(0);const [selected,setSelected]=useState<string|null>(null);
 const [brand,setBrand]=useState('CU');const [budget,setBudget]=useState(0);
 const [failedImages,setFailedImages]=useState<string[]>([]);
 const meals=groups[mode].filter(p=>mode!=='ready'||(p.price!==null&&p.price>0&&!!p.image&&!failedImages.includes(p.id)&&p.brand===brand&&(!budget||(p.price!==null&&p.price<=budget))));const visible=Array.from({length:Math.min(3,meals.length)},(_,i)=>meals[(offset+i)%meals.length]);
 return <main className="prep-preview"><header><Link href="/">끼니플랜.</Link><span>로컬 체험 시안</span></header><section className="prep-intro"><small>퇴근 후, 나에게 맞는 한 끼</small><h1>오늘은 얼마나<br/>준비할 수 있나요?</h1><p>힘이 남는 만큼만. 오늘의 한 끼를 골라요.</p></section><fieldset className="prep-options"><legend>식사 준비 방식</legend>{options.map(o=><button key={o.id} type="button" aria-pressed={mode===o.id} onClick={()=>{setMode(o.id);setOffset(0);setSelected(null);}}><span aria-hidden="true">{o.icon}</span><span><strong>{o.title}</strong><small>{o.sub}</small></span><b aria-hidden="true">{mode===o.id?'✓':'○'}</b></button>)}</fieldset>
 <section className="prep-results" aria-live="polite"><div className="prep-result-heading"><h2>{mode==='ready'?'오늘은 편의점에서 한 끼':mode==='simple'?'준비 부담이 적은 메뉴':'직접 만드는 한 끼'}</h2><button disabled={meals.length<4} onClick={()=>{setOffset((offset+3)%meals.length);setSelected(null);}}>다른 메뉴 ↻</button></div>
 {mode==='ready'?<><div className="prep-store-picker" aria-label="편의점 선택">{['CU','GS25','세븐일레븐'].map(b=><button key={b} aria-pressed={brand===b} onClick={()=>{setBrand(b);setOffset(0);setSelected(null);}}>{b}</button>)}</div><label className="prep-budget">한 끼 예산 <select value={budget} onChange={e=>{setBudget(Number(e.target.value));setOffset(0);setSelected(null);}}><option value={0}>전체</option><option value={4000}>4,000원 이하</option><option value={6000}>6,000원 이하</option><option value={8000}>8,000원 이하</option></select><span>{meals.length}개 상품</span></label><p className="prep-note">{brand} 실제 상품으로 골랐어요. 매장별 재고는 다르며, 데우는 방법은 포장 안내를 따라주세요.</p></>:<p className="prep-note">{mode==='simple'?'재료와 조리 단계로 추린 후보예요. 실제 준비 시간은 달라요.':'재료와 만드는 방법을 보고 오늘 할 수 있는 메뉴를 골라보세요.'}</p>}

 {visible.length===0&&<p className="prep-notice">조건이 확인된 메뉴를 아직 준비하지 못했어요. 다른 준비 방식을 골라보세요.</p>}
 <div className="prep-cards">{visible.map(p=><article key={p.id} className={selected===p.id?'selected':''}>{p.image?<img src={p.image} alt={p.name} loading="lazy" onError={()=>{if(mode==='ready'){setFailedImages(ids=>ids.includes(p.id)?ids:[...ids,p.id]);setOffset(0);}}}/>:<div className="prep-image-empty" aria-hidden="true">{options.find(o=>o.id===mode)?.icon}</div>}<div className="prep-card-body"><span className="prep-badge">{mode==='ready'?p.brand:mode==='simple'?'간단 조리 후보':'직접 요리'}</span><h3>{p.name}</h3><p className="prep-price">{p.price===null?'가격 확인 중':`${p.price.toLocaleString('ko-KR')}원`}</p><small>{p.note}</small>{p.checkedAt&&<small>출처 확인 {p.checkedAt.slice(0,10)} · 매장 재고 미확인</small>}{mode==='ready'&&<small>영양정보 미확인 · 영양 맞춤 추천에는 아직 미반영</small>}{mode!=='ready'&&<details><summary>재료 · 만드는 방법</summary><p>{p.ingredients.join(' · ')}</p><ol>{p.steps.map((s,i)=><li key={i}>{s}</li>)}</ol></details>}{p.url?<a href={p.url} target="_blank" rel="noopener noreferrer">공식 상품 출처 ↗</a>:null}<button onClick={()=>setSelected(p.id)}>{selected===p.id?'✓ 오늘의 한 끼로 골랐어요':'오늘은 이 메뉴'}</button></div></article>)}</div>
 {selected&&<p className="prep-selection" role="status">이 화면에서만 선택했어요. 저장된 식단과 기록은 바뀌지 않아요.</p>}</section>
 <details className="prep-data"><summary>상품 출처와 확인 범위</summary><p>CU·세븐일레븐 공식 상품 목록과 GS25 공식 출시 보도자료에서 총 {counts.ready}개를 가져왔어요. 상품명·가격·사진은 출처에 있는 정보만 사용했습니다. GS25 일부 상품은 가격이 없어 예산 필터에서 제외됩니다.</p><p>출처 확인일 2026-09-27. 실시간 재고 연동은 아니며, 영양정보와 개별 가열 시간은 아직 미확인입니다. 사진은 로컬 시안에서 공식 원본을 참조합니다.</p><p>선택 결과는 이 화면에서만 유지됩니다. 운영 추천·계정·장바구니에는 반영하지 않습니다.</p></details></main>;
}
