"use client";
import { useEffect, useState } from "react";
import { dietStyles } from "../lib/meal-plan";
import type { CatalogItem } from "../lib/catalog";
import type { CommunityData } from "../lib/community";
const won=(n:number)=>`${n.toLocaleString("ko-KR")}원`;
export function CommunityPanel({userId,products,budget,onLogin,onProfile,onCart}:{userId?:string;products:CatalogItem[];budget:number;onLogin:()=>void;onProfile:()=>void;onCart:()=>void}) {
 const [data,setData]=useState<CommunityData|null>(null);
 const [error,setError]=useState("");const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);
 const [section,setSection]=useState<"baskets"|"challenges">("baskets");const [compose,setCompose]=useState(false);
 const [alias,setAlias]=useState("");const [title,setTitle]=useState("");const [body,setBody]=useState("");const [style,setStyle]=useState("balanced");
 const [selected,setSelected]=useState<string[]>(products.map(p=>p.id));const [tipPost,setTipPost]=useState<string|null>(null);const [tip,setTip]=useState("");
 const [adoptId,setAdoptId]=useState<string|null>(null);const [limit,setLimit]=useState(String(budget));
 async function load(){const r=await fetch("/api/community",{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error);setData(d);}
 useEffect(()=>{const c=new AbortController();fetch("/api/community",{cache:"no-store",signal:c.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);if(!c.signal.aborted)setData(d);}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[userId]);
 async function act(payload:Record<string,unknown>,success:string){
  if(!userId){onLogin();return false;} if(busy)return false;setBusy(true);setError("");setMessage("");
  try{const r=await fetch("/api/community",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw new Error(d.error);setMessage(d.message??success);await load();return true;}
  catch(e){setError(e instanceof Error?e.message:"다시 시도해 주세요.");return false;}finally{setBusy(false);}
 }
 return <div className="community"><div className="page-intro"><div className="week-label">우리의 작은 식탁</div><h2>같이 먹고, <span>같이 아껴요.</span></h2><p>잘 먹는 방법을 나누면 한 주가 조금 쉬워져요.</p></div>
  <div className="community-hero"><span aria-hidden="true">🥕 🥦 🍚</span><h3>혼자 차려도, 함께하는 한 끼</h3><p>장바구니부터 냉장고 속 작은 팁까지.</p><button onClick={()=>{if(!userId)onLogin();else setCompose(!compose);}}>내 장바구니 공유하기 ＋</button></div>
  <div className="community-tabs"><button aria-pressed={section==="baskets"} onClick={()=>setSection("baskets")}>장바구니 & 팁</button><button aria-pressed={section==="challenges"} onClick={()=>setSection("challenges")}>주간 챌린지</button></div>
  {error&&<p role="alert" className="auth-error">{error} <button className="text-link" onClick={()=>{setError("");void load().catch(e=>setError(e.message));}}>다시 불러오기</button></p>}
  {message&&<p role="status" className="community-message">{message}</p>}
  {compose&&<form className="community-compose" onSubmit={async e=>{e.preventDefault();if(await act({action:"share",alias,title,body,style,items:selected},"장바구니를 공유했어요.")){setCompose(false);setTitle("");setBody("");setSection("baskets");}}}><h3>나의 장보기 이야기</h3><p>선택한 상품·별명·후기만 공개돼요. 신체 정보와 월급은 공유하지 않아요.</p><fieldset disabled={busy}><label>공개 별명<input required maxLength={24} value={alias} onChange={e=>setAlias(e.target.value)} placeholder="예: 두부좋아"/></label><label>제목<input required maxLength={80} value={title} onChange={e=>setTitle(e.target.value)} placeholder="이번 주는 냉장고 비우는 주간!"/></label><label>식단 스타일<select value={style} onChange={e=>setStyle(e.target.value)}>{Object.entries(dietStyles).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><div className="community-products">{products.map(p=><label key={p.id}><input type="checkbox" checked={selected.includes(p.id)} onChange={()=>setSelected(v=>v.includes(p.id)?v.filter(x=>x!==p.id):[...v,p.id])}/><span>{p.emoji} {p.name}</span><small>{won(p.price)}</small></label>)}</div><label>나만의 장보기 팁<textarea required maxLength={1000} value={body} onChange={e=>setBody(e.target.value)} placeholder="소분 방법, 대체 재료, 직접 먹어본 이야기를 남겨요."/></label><button className="primary-button" disabled={!selected.length}>공유하기</button><button type="button" className="text-link" onClick={()=>setCompose(false)}>취소</button></fieldset></form>}
  {!data&&!error&&<p role="status">이웃들의 식탁을 불러오는 중이에요…</p>}
  {section==="baskets"&&data&&<>{data.posts.length===0&&<div className="community-empty"><span>🧺</span><h3>첫 번째 식탁의 주인공이 되어 주세요</h3><p>아직 공유된 장바구니가 없어요.<br/>이번 주 잘 산 재료와 작은 팁을 나눠 보세요.</p></div>}{data.posts.map(post=><article className="community-post" key={post.id}><header><span className="community-avatar">🍙</span><div><strong>{post.alias}</strong><small>{new Date(post.createdAt).toLocaleDateString("ko-KR",{timeZone:"Asia/Seoul"})} · {dietStyles[post.style as keyof typeof dietStyles]}</small></div>{post.mine&&<button disabled={busy} className="text-link" onClick={()=>{if(window.confirm("이 장바구니와 달린 팁을 삭제할까요?"))void act({action:"delete-post",postId:post.id},"삭제했어요.");}}>삭제</button>}</header><h3>{post.title}</h3><p className="community-body">{post.body}</p><div className="community-basket"><div><strong>{won(post.items.reduce((n,i)=>n+i.price,0))}</strong><small>공유 당시 가격 · {post.items.length}개 상품</small></div><div className="community-item-tags">{post.items.map(i=><span key={i.id}>{i.emoji} {i.name}</span>)}</div></div><div className="community-actions"><button aria-pressed={post.liked} disabled={busy} onClick={()=>void act({action:"like",postId:post.id,liked:!post.liked},post.liked?"반응을 취소했어요.":"도움됐다는 마음을 전했어요.")}>{post.liked?"♥":"♡"} 도움됐어요 {post.likes}</button><button onClick={()=>{if(!userId)onLogin();else {setAdoptId(adoptId===post.id?null:post.id);setLimit(String(budget));}}}>내 조건으로 담기 →</button></div>
  {adoptId===post.id&&<form className="community-adopt" onSubmit={async e=>{e.preventDefault();if(await act({action:"adopt",postId:post.id,budget:Number(limit)},"담았어요."))setAdoptId(null);}}><label>이번 장보기 예산<input type="number" min={1000} max={10000000} required value={limit} onChange={e=>setLimit(e.target.value)}/></label><p>현재 상품 가격과 내 제외 재료를 반영해 예산 내 상품을 담아요. 기존 ‘따라 담은 장바구니’를 교체하고 내 칼로리 기준 식단도 저장해요. 상품 구성만으로 하루 영양 충족을 보장하지 않아요.</p><button disabled={busy} className="primary-button">조건 반영해서 저장</button><button type="button" className="text-link" onClick={onProfile}>내 신체 정보·취향 설정 →</button></form>}
  <details className="community-tips"><summary>대체·소분 팁 {post.tips.length}개</summary>{post.tips.map(t=><div className="community-tip" key={t.id}><strong>{t.alias}</strong><p>{t.body}</p>{t.mine&&<button className="text-link" disabled={busy} onClick={()=>void act({action:"delete-tip",tipId:t.id},"팁을 삭제했어요.")}>삭제</button>}</div>)}{tipPost===post.id?<form onSubmit={async e=>{e.preventDefault();if(await act({action:"tip",postId:post.id,alias,body:tip},"팁을 남겼어요.")){setTip("");setTipPost(null);}}}><label>공개 별명<input required maxLength={24} value={alias} onChange={e=>setAlias(e.target.value)}/></label><label>나누고 싶은 팁<textarea required maxLength={500} value={tip} onChange={e=>setTip(e.target.value)} placeholder="어떤 재료를 어떻게 바꾸면 좋을까요?"/></label><button disabled={busy} className="primary-button">팁 남기기</button></form>:<button className="text-link" onClick={()=>{if(!userId)onLogin();else{setTipPost(post.id);setTip("");}}}>＋ 나의 팁 나누기</button>}</details></article>)}{data.basket&&<button className="meal-refresh" onClick={onCart}>따라 담은 내 장바구니 보기 →</button>}</>}
  {section==="challenges"&&data&&<><p className="community-caption">{data.week} 시작 주간 · 매주 월요일 새로 시작해요.</p><div className="community-challenge-intro"><h3>나의 속도로, 함께 해요 🌱</h3><p>하루 한 번 직접 체크해요. 체중이나 지출 순위 없이 작은 실천을 응원해요.</p></div>{data.challenges.map((c,i)=><article className="community-challenge" key={c.id}><span className="challenge-emoji">{["🥣","🍳","🥦"][i]}</span><h3>{c.title}</h3><p>{c.description}</p><small>{c.members}명 함께하는 중</small><div className="challenge-progress"><span style={{width:`${Math.min(100,c.progress/c.target*100)}%`}}/></div><div className="challenge-bottom"><strong>{c.joined?`${Math.min(c.progress,c.target)} / ${c.target}일`:`목표 ${c.target}일`}</strong><button disabled={busy||(!c.checked&&c.progress>=c.target)} onClick={()=>void act(c.joined?{action:"check",challengeId:c.id,checked:!c.checked}:{action:"join",challengeId:c.id},c.joined?(c.checked?"오늘 체크를 취소했어요.":"오늘도 한 걸음 완료! 🌱"):"이번 주 챌린지에 참여했어요.")}>{!c.joined?"함께 시작하기":c.checked?"오늘 완료 ✓ · 취소":c.progress>=c.target?"이번 주 달성 🎉":"오늘 실천했어요"}</button></div></article>)}</>}
 </div>;
}
export function SharedBasket({userId,onCompare}:{userId?:string;onCompare:(id:string)=>void}) {
 const [basket,setBasket]=useState<CommunityData["basket"]>(null);const [error,setError]=useState("");
 useEffect(()=>{if(!userId)return;const c=new AbortController();fetch("/api/community",{cache:"no-store",signal:c.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);if(!c.signal.aborted)setBasket(d.basket);}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[userId]);
 if(error)return <p role="alert">따라 담은 장바구니를 불러오지 못했어요.</p>;
 if(!basket)return null;
 return <section className="community-saved"><span className="section-kicker">이웃의 식탁에서 내 식탁으로</span><h3>따라 담은 장바구니</h3><p>{won(basket.items.reduce((n,i)=>n+i.price,0))} / 예산 {won(basket.budget)}</p>{basket.items.map(i=><button key={i.id} onClick={()=>onCompare(i.id)}><span>{i.emoji} {i.name}</span><b>{won(i.price)} ↗</b></button>)}<small>저장 당시 가격 · 아래 기본 추천과 별도로 보관해요. 구매 전 가격을 확인해 주세요.</small></section>;
}
