"use client";
import { useState } from "react";
import { AppLoading } from "./app-loading";
import { addDays,expenseCategories,type DashboardData } from "../lib/dashboard";
import type { CatalogItem } from "../lib/catalog";
import { BudgetBuddy, RiceBuddy } from "./rice-buddy";
import { ProductThumb } from "./product-thumb";
const won=(n:number)=>`${n.toLocaleString("ko-KR")}원`;
export function Dashboard({mode,data,userId,products,onLogin,onProfile,onCart,onCalendar,onBudget,onRefresh,onCompare,recordDate}:{recordDate?:string;mode:"home"|"calendar"|"record";data:DashboardData;userId?:string;products:CatalogItem[];onLogin:()=>void;onProfile:()=>void;onCart:()=>void;onCalendar:()=>void;onBudget:()=>void;onRefresh:()=>Promise<void>;onCompare:(id:string)=>void}){
 const [localDate,setSelected]=useState(data.today);const selected=recordDate??localDate;const [month,setMonth]=useState(data.today.slice(0,7));
 const [amount,setAmount]=useState("");const [category,setCategory]=useState<keyof typeof expenseCategories>("food");const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [message,setMessage]=useState("");
 const weekExpenses=data.expenses.filter(e=>e.date>=data.week&&e.date<addDays(data.week,7));const food=weekExpenses.filter(e=>e.category==="food").reduce((s,e)=>s+e.amount,0);
 const latest=data.plans.find(p=>p.date===data.today);
 const year=Number(month.slice(0,4)),m=Number(month.slice(5,7));const first=(new Date(Date.UTC(year,m-1,1)).getUTCDay()+6)%7;const days=new Date(Date.UTC(year,m,0)).getUTCDate();
 const selectedExpense=data.expenses.filter(e=>e.date===selected);const selectedPurchases=(data.purchases??[]).filter(p=>p.date===selected);
 const weekly=Array.from({length:4},(_,i)=>{const start=addDays(data.week,(i-3)*7);return {start,total:data.expenses.filter(e=>e.date>=start&&e.date<addDays(start,7)).reduce((s,e)=>s+e.amount,0)};});
 const max=Math.max(1,...weekly.map(w=>w.total));
 const budgetPercent=data.budget?Math.min(100,Math.round(food/data.budget*100)):0;
 async function save(e:React.FormEvent){e.preventDefault();if(!userId){onLogin();return;}setBusy(true);setError("");setMessage("");try{const r=await fetch("/api/dashboard",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"expense",date:selected,category,amount:Number(amount)})});const d=await r.json();if(!r.ok)throw new Error(d.error);await onRefresh();setMessage("기록을 저장했어요.");}catch(e){setError(e instanceof Error?e.message:"저장에 실패했어요.");}finally{setBusy(false);}}
 return <>{busy&&<AppLoading message="오늘의 지출을 저장하고 있어요"/>}{mode!=="home"&&<div className="page-intro"><div className="week-label">{mode==="calendar"?month:`${data.week} 시작 주간`}</div><h2>{mode==="calendar"?<>하루하루 <span>나의 식탁</span></>:<>차곡차곡 <span>생활비 기록</span></>}</h2><p>{mode==="calendar"?"구매를 기록한 날짜와 일별 지출을 확인해요.":"실제 결제한 금액을 보는 곳이에요. 먹은 음식의 예상 비용은 위의 섭취 기록에서 확인해 주세요."}</p></div>}
 {!userId&&<button className="personal-home-link" onClick={onLogin}>로그인하고 나의 식단·지출 기록 시작하기 →</button>}
 {mode==="home"&&<>{data.budget!==null?<BudgetBuddy budget={data.budget} spent={food} cart={products.filter(p=>p.inWeeklyCart).reduce((s,p)=>s+p.price,0)} onEdit={onBudget}/>:<div className="community-hero home-budget-empty"><RiceBuddy/><div><h3>이번 주 식비, 얼마로 시작할까요?</h3><p>예산을 정하면 장보기와 식단을 한눈에 관리할 수 있어요.</p><button onClick={onBudget}>내 식비 예산 설정 →</button></div></div>}
 <div className="section-heading home-week-heading"><div><span className="section-kicker">매일 맛있게</span><h3>이번 주 식단 달력</h3></div><button className="text-link" onClick={onCalendar}>달력 보기 →</button></div>
 <div className="week-strip">{Array.from({length:7},(_,i)=>{const date=addDays(data.week,i);const planned=data.plans.some(p=>p.date===date);return <button type="button" key={date} className={`week-day ${date===data.today?"selected":""}`} onClick={onCalendar} aria-label={`${date} 식단 달력 보기`}><span>{"월화수목금토일"[i]}</span><strong>{Number(date.slice(-2))}</strong><i className={planned?"recorded":""}/></button>})}</div>
 <button className="personal-home-link" onClick={onProfile}><span>🥣</span><div><strong>{latest?`오늘의 식단 ${latest.recommendation.meals.length}끼`:"내 몸과 취향에 맞는 한 끼"}</strong><small>{latest?`예상 ${latest.recommendation.total} kcal · 단백질 ${latest.recommendation.protein}g`:"필요 칼로리 · 식사 횟수 · 맞춤 식단"}</small></div><b>→</b></button>
 {latest&&<div className="today-preview"><span className="today-preview-icon">{latest.recommendation.meals[0]?.emoji??"🍽️"}</span><div><small>오늘의 식단</small><strong>{latest.recommendation.meals[0]?.name??"나만의 식단"}</strong><span>예상 {latest.recommendation.total} kcal · 단백질 {latest.recommendation.protein}g</span></div></div>}
 <div className="section-heading"><div><span className="section-kicker">차곡차곡 쌓이는 중</span><h3>이번 주 현황</h3></div><button className="text-link" onClick={onCalendar}>기록 보기 →</button></div>
 <div className="metrics"><div className="metric"><div className="metric-top"><span className="metric-icon wallet">▣</span><span className="metric-label">식비 사용</span></div><div className="metric-value">{budgetPercent}<span>%</span></div><div className="metric-track"><span style={{width:`${budgetPercent}%`}}/></div><div className="metric-foot">{won(food)} 사용 · 예산 {data.budget!==null?won(data.budget):"미설정"}</div></div><div className="metric"><div className="metric-top"><span className="metric-icon fire">♨</span><span className="metric-label">오늘 식단 단백질</span></div><div className="metric-value">{latest?latest.recommendation.protein:"—"}<span>{latest?"g":""}</span></div><div className="metric-foot">{latest?"생성한 식단의 예상량":"식단을 만들면 보여요"}</div></div></div>
 <div className="section-heading"><h3>지금 장볼 수 있는 상품</h3><button className="text-link" onClick={onCart}>전체 보기 →</button></div><div className="food-list">{products.slice(0,4).map(p=><button className="food-row" key={p.id} onClick={()=>onCompare(p.id)}><ProductThumb item={p}/><span className="food-meta"><strong>{p.name}</strong><small>{p.detail}</small></span><span className="food-price"><strong>{won(p.price)}{p.priceNote?.includes("시작가")?"~":""}</strong></span></button>)}</div></>}
 {mode==="record"&&<><div className="record-summary"><span>이번 주 결제한 생활비</span><strong>{won(weekExpenses.reduce((s,e)=>s+e.amount,0))}</strong><p>식비 {won(food)} · {new Set(weekExpenses.map(e=>e.date)).size}일 기록</p></div><section className="living-trend"><h3>최근 4주 생활비</h3><div className="real-expense-chart">{weekly.map(w=><div key={w.start}><strong>{won(w.total)}</strong><div><span style={{height:`${w.total/max*100}%`}}/></div><small>{w.start.slice(5)} 주</small></div>)}</div><p className="body-note">입력한 지출 합계예요. 기록하지 않은 지출은 포함되지 않아요.</p>{weekly[2].total>0&&<p>지난주 대비 {won(Math.abs(weekly[3].total-weekly[2].total))} {weekly[3].total>=weekly[2].total?"늘었어요":"줄었어요"}.</p>}</section><div className="cart-stats">{Object.entries(expenseCategories).map(([key,label])=><div key={key}><strong>{won(weekExpenses.filter(e=>e.category===key).reduce((s,e)=>s+e.amount,0))}</strong><span>{label}</span></div>)}</div></>}
 {mode!=="home"&&<>{mode==="calendar"?<section className="calendar-card"><div className="calendar-title"><h3>{year}년 {m}월</h3><div className="month-controls"><button aria-label="이전 달" onClick={()=>setMonth(new Date(Date.UTC(year,m-2,1)).toISOString().slice(0,7))}>‹</button><button onClick={()=>{setMonth(data.today.slice(0,7));setSelected(data.today);setAmount("");}}>오늘</button><button aria-label="다음 달" onClick={()=>setMonth(new Date(Date.UTC(year,m,1)).toISOString().slice(0,7))}>›</button></div></div><div className="calendar-weekdays">{"월화수목금토일".split("").map(d=><span key={d}>{d}</span>)}</div><div className="calendar-grid">{Array.from({length:first},(_,i)=><span key={`blank-${i}`}/>)}{Array.from({length:days},(_,i)=>{const date=`${month}-${String(i+1).padStart(2,"0")}`;const purchases=(data.purchases??[]).filter(p=>p.date===date);const expenses=data.expenses.filter(e=>e.date===date);return <button key={date} className={`calendar-cell ${date===selected?"is-active":""}`} onClick={()=>{setSelected(date);setAmount("");setMessage("");}}><strong>{i+1}</strong>{!!purchases.length&&<small>구매 {purchases.length}건</small>}{expenses.length>0&&<small>{won(expenses.reduce((s,e)=>s+e.amount,0))}</small>}</button>})}</div></section>:!recordDate&&<label className="real-date">기록 날짜<input type="date" value={selected} onChange={e=>{setSelected(e.target.value);setAmount("");setMessage("");}}/></label>}
 <div className="day-head"><h3>{selected}</h3><span>{selectedExpense.length?won(selectedExpense.reduce((s,e)=>s+e.amount,0)):"지출 기록 없음"}</span></div>
 <section aria-label="실제 구매 기록"><h3>구매한 음식 · 결제 기록</h3>{selectedPurchases.length?<><div className="meal-list">{selectedPurchases.map(p=><div className="meal-row" key={p.id}><span className="meal-emoji" aria-hidden="true">🧺</span><div className="meal-info"><small>{p.action==='order'?'주문 시 기록':p.action==='backfill'?'이전 구매금액 추가 기록':'직접 구매 기록'}</small><strong>{p.names.join(' · ')}</strong><span>{won(p.amount)}</span></div></div>)}</div><p className="body-note">구매할 때 확인한 금액이에요. 하루 합계를 직접 수정했다면 아래 식비 합계와 다를 수 있어요.</p></>:<p className="body-note">이날 기록한 구매 내역이 없어요. 장바구니에서 구매금액을 기록하면 여기에 표시돼요. 이미 보유 중인 음식은 ‘구매금액 기록하기’를 이용해 주세요.</p>}<button type="button" className="text-link" onClick={onCart}>장바구니에서 구매 기록하기 →</button></section>
 <form className="real-expense-form" onSubmit={save}><h3>이날 지출 기록</h3><p>구매 시 기록한 식비도 포함된 하루 합계예요. 수정할 때는 추가 금액이 아닌 하루 전체 금액을 입력해 주세요.</p><label>지출 항목<select value={category} onChange={e=>{setCategory(e.target.value as typeof category);setAmount("");}}>{Object.entries(expenseCategories).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>하루 합계 (원)<input type="number" required min="0" max="10000000" value={amount} placeholder={String(selectedExpense.find(e=>e.category===category)?.amount??0)} onChange={e=>setAmount(e.target.value)}/></label><button className="primary-button" disabled={busy||!selected}>{busy?"저장 중…":"지출 저장"}</button>{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}</form>
 {selectedExpense.map(e=><div className="real-expense-row" key={e.category}><span>{expenseCategories[e.category]}</span><b>{won(e.amount)}</b></div>)}</>}
 </>;
}
