// Food kind is independent of preparation/storage category. Unknown names stay unclassified.
export const foodTypes = {
  "chicken_breast": "닭가슴살",
  "chicken_other": "닭안심·기타 닭고기",
  "lunch_box": "도시락",
  "fried_rice": "볶음밥",
  "rice": "밥·즉석밥",
  "porridge": "죽·스프",
  "noodles": "면·파스타",
  "soup": "국·탕·찌개",
  "salad": "샐러드",
  "sandwich": "샌드위치·버거",
  "bread": "빵·베이커리",
  "cereal": "시리얼·그래놀라",
  "oats": "오트밀",
  "milk": "우유",
  "soy_milk": "두유·식물성 음료",
  "yogurt": "요거트",
  "cheese": "치즈",
  "egg": "달걀",
  "tofu": "두부·콩",
  "beef": "소고기",
  "pork": "돼지고기",
  "fish": "생선·해산물",
  "vegetables": "채소·버섯",
  "fruit": "과일",
  "nuts": "견과류",
  "protein_drink": "단백질 음료·파우더",
  "protein_snack": "단백질 바·간식",
  "dumplings": "만두",
  "pizza": "피자",
  "side_dish": "반찬·김치",
  "sauce_oil": "소스·조미료·오일",
  "snack": "간식·디저트",
  "drink": "음료",
  "other": "기타 음식"
} as const;
export type FoodType = keyof typeof foodTypes;
export const isFoodType = (value: unknown): value is FoodType => typeof value === 'string' && Object.hasOwn(foodTypes,value);
const rules: [FoodType,RegExp][] = [
  ['sauce_oil',new RegExp("올리브유|참기름|들기름|식용유|치킨스톡|드레싱",'i')],
  ['lunch_box',new RegExp("도시락",'i')],
  ['fried_rice',new RegExp("볶음밥",'i')],
  ['sandwich',new RegExp("샌드위치|버거",'i')],
  ['pizza',new RegExp("피자",'i')],
  ['dumplings',new RegExp("만두",'i')],
  ['soup',new RegExp("찌개|전골|곰탕|설렁탕|삼계탕|갈비탕|육개장|미역국|된장국|해장국|떡국",'i')],
  ['porridge',new RegExp("(?:전복|야채|채소|단호박|소고기|닭|참치|흑임자|버섯)죽|스프|수프",'i')],
  ['noodles',new RegExp("파스타|스파게티|국수|칼국수|우동|라면|쌀국수|두부면|곤약면|비빔면|냉면|메밀면",'i')],
  ['salad',new RegExp("샐러드",'i')],
  ['protein_snack',new RegExp("(?:단백질|프로틴)\\s*(?:바|칩|쿠키|볼)|프로틴바",'i')],
  ['protein_drink',new RegExp("단백질|프로틴|웨이\\s*프로틴",'i')],
  ['cereal',new RegExp("시리얼|씨리얼|그래놀라|콘푸라이트|콘푸로스트|뮤즐리",'i')],
  ['oats',new RegExp("오트밀",'i')],
  ['bread',new RegExp("식빵|베이글|크루아상|모닝빵|통밀빵|호밀빵|베이커리",'i')],
  ['yogurt',new RegExp("요거트|요구르트",'i')],
  ['soy_milk',new RegExp("두유|아몬드\\s*브리즈|오트\\s*(?:드링크|음료|밀크)",'i')],
  ['milk',new RegExp("우유",'i')],
  ['cheese',new RegExp("치즈",'i')],
  ['chicken_breast',new RegExp("닭\\s*가슴살",'i')],
  ['chicken_other',new RegExp("닭안심|닭다리|닭고기|생닭",'i')],
  ['rice',new RegExp("현미밥|즉석밥|햇반|쌀밥|잡곡밥|곤약밥",'i')],
  ['egg',new RegExp("계란|달걀|구운란|반숙란",'i')],
  ['tofu',new RegExp("두부|병아리콩|렌틸콩",'i')],
  ['beef',new RegExp("소고기|쇠고기|한우",'i')],
  ['pork',new RegExp("돼지고기|삼겹살|목살|한돈",'i')],
  ['fish',new RegExp("연어|고등어|참치|새우|오징어|명태|대구살",'i')],
  ['side_dish',new RegExp("김치|장조림|나물|반찬",'i')],
  ['vegetables',new RegExp("브로콜리|양배추|시금치|양상추|채소|버섯",'i')],
  ['fruit',new RegExp("바나나|사과|블루베리|딸기|키위",'i')],
  ['nuts',new RegExp("견과|아몬드|호두|캐슈넛",'i')],
  ['snack',new RegExp("쿠키|과자|초콜릿|아이스크림",'i')],
  ['drink',new RegExp("주스|커피|탄산수",'i')]
];
export function inferFoodType(name: string): FoodType | null {
  return rules.find(([,pattern])=>pattern.test(name))?.[0]??null;
}
