CREATE TABLE IF NOT EXISTS pantry_inventory (
 user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
 inventory JSONB NOT NULL DEFAULT '[]',
 version INTEGER NOT NULL DEFAULT 0,
 request_id TEXT,
 updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE pantry_inventory ENABLE ROW LEVEL SECURITY;
