ALTER TABLE manual_meal_plans ADD COLUMN IF NOT EXISTS nutrition JSONB;
CREATE TABLE IF NOT EXISTS plan_photo_usage (
 user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 day DATE NOT NULL, attempts INTEGER NOT NULL DEFAULT 0,
 PRIMARY KEY(user_id,day)
);
ALTER TABLE plan_photo_usage ENABLE ROW LEVEL SECURITY;
