'use client';
import {useCallback,useEffect,useState} from 'react';
type Run={id:string;status:string;started_at:string;scanned:number;published:number;ended:number;errors:number;message:string};
type State={enabled:boolean;source:string;schedule:string;candidates:number;runs:Run[]};
export function CollectionPanel({onCollected}:{onCollected:()=>Promise<void>}){
 const [state,setState]=useState<State>(),[busy,setBusy]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(''),[result,setResult]=useState('');
 const refresh=useCallback(async()=>{const r=await fetch('/api/admin/food-deals/collect',{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error);setState(d);},[]);
 useEffect(()=>{const c=new AbortController();void fetch('/api/admin/food-deals/collect',{cache:'no-store',signal:c.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setState(d);}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[]);
 useEffect(()=>{if(!busy&&state?.runs[0]?.status!=='running')return;const timer=setInterval(()=>{void refresh().catch(()=>{});},5000);return()=>clearInterval(timer);},[busy,state?.runs,refresh]);
 async function collect(){setBusy(true);setError('');setResult('');try{const r=await fetch('/api/admin/food-deals/collect',{method:'POST'});const d=await r.json();if(!r.ok)throw new Error(d.error);setResult(`${d.scanned}개 확인 · 할인 상품 ${d.published}개 등록·갱신 · 종료 ${d.ended}개`);await onCollected();}catch(e){setError(e instanceof Error?e.message:'수집 실패');}finally{setBusy(false);void refresh().catch(()=>{});}}
 async function toggle(){setSaving(true);setError('');try{const r=await fetch('/api/admin/food-deals/collect',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled:!state?.enabled})});if(!r.ok)throw new Error('자동 수집 설정을 저장하지 못했어요.');await refresh();}catch(e){setError(e instanceof Error?e.message:'설정 실패');}finally{setSaving(false);}}
 const running=busy||!!state?.runs.some(r=>r.status==='running');
 return <section className="collection-panel"><h2>할인 상품 자동 수집</h2><p>식재료·냉동식품·밀키트의 정상가와 판매가를 확인하고, 할인 상품을 자동 공개합니다. 할인율 높은 순으로 보여요.</p><p><b>연결 판매처: 컬리</b> · 공개 상품 페이지 기준 · 쿠폰 추가 할인 제외</p><div className="collection-actions"><button type="button" disabled={!state||running} onClick={collect}>{running?'수집 중…':'지금 할인 상품 수집'}</button><button type="button" disabled={!state||saving} onClick={toggle} aria-pressed={state?.enabled??false}>매일 자동 수집 {state?.enabled?'켜짐 · 끄기':'꺼짐 · 켜기'}</button></div><p>{state?.schedule} · 탐색 대상 {state?.candidates.toLocaleString()??'—'}개</p><small>버튼은 약 45초 동안 수집하고 다음 실행에서 이어집니다. 매일 자동 수집은 최대 2,500개를 확인합니다. 옵션별 가격이 다르거나 조건을 확인할 수 없는 상품은 제외합니다. 전체 쇼핑몰 최저가 순위는 아닙니다.</small>{error&&<p role="alert">{error}</p>}{result&&<p role="status">{result}</p>}<details><summary>최근 수집 기록</summary>{state?.runs.length?state.runs.map(r=><article key={r.id}><strong>{{running:'진행 중',success:'완료',partial:'일부 확인 실패',failed:'실패'}[r.status]??r.status}</strong> · {new Date(r.started_at).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})}<p>확인 {r.scanned} · 등록·갱신 {r.published} · 종료 {r.ended} · 오류 {r.errors}</p><small>{r.message}</small></article>):<p>아직 수집 기록이 없어요.</p>}</details></section>;
}
