'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {foodTypes} from '../../../lib/catalog-food-types';
import {dealState,type FoodDeal} from '../../../lib/food-deals';
import '../../deals/style.css';
const blank={title:'',food_type:'rice',source_name:'',source_url:'',product_url:'',price:'',shipping:'',pack:'',conditions:'',product_id:'',status:'draft',ends_at:'',reviewed:false};
export default function DealAdmin(){
 const [items,setItems]=useState<FoodDeal[]>([]),[products,setProducts]=useState<{id:string;name:string}[]>([]),[form,setForm]=useState(blank),[id,setId]=useState<string|undefined>(),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false),[filter,setFilter]=useState('all');
 async function load(){const r=await fetch('/api/admin/food-deals',{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.error);setItems(d.items);}
 useEffect(()=>{const c=new AbortController();void fetch('/api/admin/food-deals',{signal:c.signal,cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setItems(d.items);const catalog=await fetch('/api/catalog',{signal:c.signal});if(catalog.ok)setProducts((await catalog.json()).items??[]);}).catch(e=>{if(!c.signal.aborted)setError(e.message);}).finally(()=>{if(!c.signal.aborted)setLoaded(true);});return()=>c.abort();},[]);
 function edit(d:FoodDeal){setId(d.id);setForm({title:d.title,food_type:d.food_type,source_name:d.source_name,source_url:d.source_url,product_url:d.product_url,price:String(d.price),shipping:d.shipping===null?'':String(d.shipping),pack:d.pack,conditions:d.conditions,product_id:d.product_id??'',status:d.status,ends_at:d.ends_at?new Date(Date.parse(d.ends_at)+9*3600000).toISOString().slice(0,16):'',reviewed:false});setMessage('');window.scrollTo({top:0,behavior:'smooth'});}
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');setMessage('');try{const payload={...form,id,price:Number(form.price),shipping:form.shipping===''?null:Number(form.shipping),product_id:form.product_id||null,ends_at:form.ends_at?new Date(form.ends_at+':00+09:00').toISOString():null};const r=await fetch('/api/admin/food-deals',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),d=await r.json();if(!r.ok)throw new Error(d.error);setId(undefined);setForm(blank);await load();setMessage('저장했어요. 공개 항목은 핫딜 페이지에서 확인할 수 있어요.');}catch(e){setError(e instanceof Error?e.message:'저장 실패');}finally{setBusy(false);}}
 const update=(key:keyof typeof blank,value:string|boolean)=>setForm(prev=>({...prev,[key]:value}));
 return <main className="deal-admin"><Link href="/admin">관리자로 돌아가기</Link> · <Link href="/deals">식품 핫딜 보기 →</Link><h1>식품 핫딜 수집·검토</h1><p>원문과 판매 링크를 등록하고 구성·가격·할인 조건을 확인한 뒤 공개하세요. 자동 크롤링은 아직 연결하지 않았습니다.</p>{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}{!loaded?<p>불러오는 중…</p>:<><form className="deal-editor" onSubmit={save}><h2 className="wide">{id?'핫딜 수정':'새 핫딜 등록'}</h2>
 {([['title','상품명',180],['source_name','출처 이름 (예: 뽐뿌·공식몰)',60],['source_url','원문 출처 HTTPS 링크',2000],['product_url','실제 구매 HTTPS 링크',2000],['pack','판매 구성 (예: 210g × 12개)',300]] as const).map(([key,label,max])=><label key={key}>{label}<input required maxLength={max} value={form[key]} type={key.endsWith('url')?'url':'text'} onChange={e=>update(key,e.target.value)}/></label>)}
 <label>음식 종류<select value={form.food_type} onChange={e=>update('food_type',e.target.value)}>{Object.entries(foodTypes).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>조건 적용 후 상품 금액 (원)<input type="number" min={1} max={10000000} step={1} required value={form.price} onChange={e=>update('price',e.target.value)}/></label><label>배송비 (무료는 0, 미확인은 빈칸)<input type="number" min={0} max={1000000} step={1} value={form.shipping} onChange={e=>update('shipping',e.target.value)}/></label><label className="wide">쿠폰·회원·결제·옵션 조건<textarea required maxLength={1500} value={form.conditions} onChange={e=>update('conditions',e.target.value)} placeholder="확인한 사실을 요약해 주세요. 커뮤니티 본문을 그대로 복사하지 마세요."/></label>
 <label>연결할 기존 상품 (선택)<select value={form.product_id} onChange={e=>update('product_id',e.target.value)}><option value="">연결 안 함</option>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>종료 시각 (한국 시간, 미확인은 빈칸)<input type="datetime-local" value={form.ends_at} onChange={e=>update('ends_at',e.target.value)}/></label><label>상태<select value={form.status} onChange={e=>update('status',e.target.value)}><option value="draft">검토 대기 (비공개)</option><option value="live">확인 후 공개</option><option value="ended">종료</option></select></label><label className="review"><input type="checkbox" checked={form.reviewed} required={form.status==='live'} onChange={e=>update('reviewed',e.target.checked)}/>현재 원문·판매 구성·가격·할인 조건을 확인했습니다.</label><p className="wide">공개 저장 시 확인 시각을 갱신합니다. 24시간 경과 또는 종료 시각 도달 시 기본 목록에서 자동으로 빠집니다. 연결 상품의 영양표와 행사 옵션은 별도로 대조하세요.</p><button disabled={busy} type="submit">{busy?'저장 중…':'저장'}</button><button type="button" disabled={busy} onClick={()=>{setId(undefined);setForm(blank);}}>입력 초기화</button></form>
 <h2>등록 목록 {items.length}건</h2><label>상태 <select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">전체</option><option value="draft">검토 대기</option><option value="live">최근 확인</option><option value="stale">재확인 필요</option><option value="ended">종료</option></select></label>{items.filter(d=>filter==='all'||dealState(d)===filter).map(d=><article key={d.id}><strong>{d.title}</strong><p>{{draft:'검토 대기',live:'최근 확인',stale:'재확인 필요',ended:'종료'}[dealState(d)]} · {d.price.toLocaleString()}원 · {d.source_name}</p><a href={d.source_url} target="_blank" rel="noopener noreferrer">원문 확인 ↗</a> · <a href={d.product_url} target="_blank" rel="noopener noreferrer">판매처 확인 ↗</a> <button onClick={()=>edit(d)}>수정·확인·종료 처리</button></article>)}</>}</main>;
}
