import Link from 'next/link';
import {notFound} from 'next/navigation';
import {getTaiwanCatalog,safeJson,twMetadata,twCategories} from '../../../../lib/taiwan-catalog';
import {twMoney} from '../../../../lib/taiwan-plan';
import {siteUrl} from '../../../../lib/seo';
type Props={params:Promise<{id:string}>};
export const revalidate=3600;
async function product(id:string){const p=(await getTaiwanCatalog()).find(p=>p.id===id);if(!p)notFound();return p;}
export async function generateMetadata({params}:Props){const p=await product((await params).id);return twMetadata(p.name+'：價格與商品資訊',`${p.name}，參考販售價格 ${twMoney(p.price)}。查看包裝說明、價格確認日期與原始賣場連結，安排台灣日常購物預算。`,'/tw/products/'+p.id);}
export default async function Page({params}:Props){const p=await product((await params).id);const path='/tw/products/'+p.id;const category=Object.entries(twCategories).find(([,v])=>v.category===p.category);const seller=p.source?.seller_name??'桂冠官方商城';const related=(await getTaiwanCatalog()).filter(x=>x.id!==p.id&&x.category===p.category).slice(0,6);
 const structured={'@context':'https://schema.org','@type':'Product',name:p.name,image:p.productImageUrl,description:p.detail,sku:p.id,offers:{'@type':'Offer',url:p.productUrl,priceCurrency:'TWD',price:p.price/100,seller:{'@type':'Organization',name:seller}}};
 return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:safeJson(structured)}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:safeJson({'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'台灣商品目錄',item:siteUrl+'/tw/products'},{'@type':'ListItem',position:2,name:p.name,item:siteUrl+path}]})}}/><nav aria-label="麵包屑"><Link href="/tw/products">所有商品</Link> / {category&&<Link href={'/tw/categories/'+category[0]}>{category[1].label}</Link>}</nav><article className="tw-product-detail"><img src={p.productImageUrl??''} alt={p.name} width="320" height="320"/><div><h1>{p.name}</h1><p className="tw-detail-price">{twMoney(p.price)}</p><p>每個販售單位 · 未含運費</p><p>{p.detail}</p><a className="tw-buy-link" href={p.productUrl!} target="_blank" rel="noopener noreferrer">到{seller}查看商品 ↗</a></div></article><section className="tw-panel"><h2>購物前先看</h2><dl><dt>銷售地區／幣別</dt><dd>台灣 · 新台幣 TWD</dd><dt>價格確認日期</dt><dd>{p.priceCheckedAt?.slice(0,10)??'尚未確認'}</dd><dt>賣場分類</dt><dd>{p.source?.category_path.join(' › ')??category?.[1].label}</dd><dt>一餐成本</dt><dd>{p.servings?`${twMoney(Math.round(p.price/Number(p.servings)))}（包裝共 ${p.servings} 份）`:'尚未確認餐數，這是販售價格，不能直接視為一餐成本。'}</dd></dl><p>買整包需要先支付完整販售金額。若分多餐使用，請依包裝實際份量分攤；家中已有的食材也要另外計算。</p><p>{p.priceNote}</p></section><section className="tw-panel"><h2>營養與成分</h2>{p.caloriesKcal!==null&&p.proteinG!==null?<p>標示基準 {p.nutritionBasis}：{p.caloriesKcal} kcal · 蛋白質 {p.proteinG}g</p>:<p>營養數值與每份重量尚未核對，請以收到的包裝標示為準。未填寫不代表零熱量或零蛋白質。</p>}{p.nutritionPhotoUrl&&<a href={p.nutritionPhotoUrl} target="_blank" rel="noopener noreferrer">原始營養標示 ↗</a>}<p>有需要避開的食材或過敏原，請先確認原包裝與賣場說明。</p></section><section className="tw-panel"><h2>也可以看看</h2><ul>{related.map(x=><li key={x.id}><Link href={'/tw/products/'+x.id}>{x.name}</Link> · {twMoney(x.price)}</li>)}</ul><Link href="/tw">用預算安排已確認份量的餐點 →</Link></section></>;
}
